[project]
name = "comfygit-registry-data"
version = "1.0.0"
description = "A repo to store and manage Comfy Registry cache data, as well as generate node_mappings.json for efficient node discovery."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
    "comfygit-core>=0.3.20",
]

[tool.uv.sources]
comfygit-core = { path = "/data/projects/comfygit-ai/comfygit/packages/core", editable = true }

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
